### ISSUE TITLE
Add standard menu bar to BaseMicroscopeApp

### ISSUE THREAD

**Issue by edbarnard** [ScopeFoundry/ScopeFoundry#1]
Add standard menu bar to BaseMicroscopeApp:

Standard Menu Bar

* File:
  * select data save directory
  * load ini file
  * save ini file
* Advanced:
  * console
  * log viewer
* help
  * about

**Comment by alanrbuckley** [comment]
In progress.

**Comment by alanrbuckley** [comment]
Commit 2a874ec61343c4da68b549deabfcf10dfd19f0d6 -> Controllers:
Added save/load .ini and ipython console menu bar QAction.

To be implemented (in base_app.py):
- select data save directory
- log viewer

**Comment by edbarnard** [comment]
Alan fixed in commit 69acf6e330c4b3e49bb87f62f64bac4b0befb6cf
