### ISSUE TITLE
Request for additional hardware/measurement components 

### ISSUE THREAD

**Issue by adpickel** [ScopeFoundry/ScopeFoundry#13]
Hi,

Thanks for the updated installation instructions on scopefoundry.org; very helpful for easy installation. I'm not sure what the timeline is on adding more hardware and measurement components here on GitHub, but it would be great to have the measurement component to do an APD scan with an MCL stage (previously, this has been called something like "APD_MCL_2DSlowScan") and the necessary hardware components to do this measurement (i.e. the APD and the MCL stage). Thanks!

**Comment by edbarnard** [comment]
The separate hardware modules are not on Github yet. We have a Foundry master repository on bitbucket that contains all the currently used hardware on the microscopes in the Molecular Foundry. Check it out here:

https://bitbucket.org/berkeleylab/foundry_scope

-Ed

**Comment by edbarnard** [comment]
Many of these Hardware components are now available on the GitHub project: https://github.com/ScopeFoundry/
