### ISSUE TITLE
HW support for CCDs

### ISSUE THREAD

**Issue by akshaybkiitb** [ScopeFoundry/ScopeFoundry#15]
Is there a ScopeFoundryHW for PI Excelon CCDs, maybe using PIcam DLLs?

**Comment by edbarnard** [comment]
Yes I have some working code with PICAM. I will upload it as a hardware component shortly.

**Comment by edbarnard** [comment]
PICAM hardware component uploaded to GitHub:

https://github.com/ScopeFoundry/HW_picam
