### ISSUE TITLE
FileLQ does not create a browse button

### ISSUE THREAD

**Issue by rbrenesh** [ScopeFoundry/ScopeFoundry#16]
Adding a FileLQ through either:

`self.settings.New('Filename', dtype = 'file')`

or:

```
from ScopeFoundry.logged_quantity import FileLQ
self.settings.Add(FileLQ('Filename'))
```

does not create a QPushButton with text "..." and browsing capabilities in the Hardware section. Instead, it only creates a QLineEdit object. Using ScopeFoundry version 1.1.1

**Comment by edbarnard** [comment]
Thanks for the bug fix. I will be working on merging it this week!

**Comment by edbarnard** [comment]
Pull request Merged on latest development ScopeFoundry. Will create a new release with this and other changes shortly.
