### ISSUE TITLE
ModuleNotFoundError: No module named 'ScopeFoundryHW'

### ISSUE THREAD

**Issue by ma-tri-x** [ScopeFoundry/ScopeFoundry#22]
I followed the basic installation guide on https://www.scopefoundry.org/building_your_first_microscope.html
and constantly get this error.

**Comment by ma-tri-x** [comment]
Sorry. was just an old command in the manual: 
should be
pip install git+https://github.com/ScopeFoundry/HW_virtual_function_gen.git
instead of
pip install git+git://github.com/ScopeFoundry/HW_virtual_function_gen.git

**Comment by edbarnard** [comment]
Thanks for the finding this bug. I've updated the instructions:

https://github.com/ScopeFoundry/scopefoundry.github.io/commit/8ce87fc71bd7f9799bc2554ac31df537ad036c2d
