### ISSUE TITLE
Cant import viewers

### ISSUE THREAD

**Issue by ercius** [ScopeFoundry/ScopeFoundry#26]
The new updates to version 1.2.2 broke the `data_browser`. 

`>>> import ScopeFoundry.data_browser` produces the error:
```
CRITICAL:root:Unhandled exception:Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\percius\Anaconda3\envs\ncem_browser\lib\site-packages\ScopeFoundry\data_browser\__init__.py", line 2, in <module>
    from .viewers.npz import NPZView
ModuleNotFoundError: No module named 'ScopeFoundry.data_browser.viewers'
```

The structure of the modules looks right. There might be something wrong with the relative imports.

**Comment by ercius** [comment]
There is a circular import created. due to the structure of the `ScopeFoundry.data_browser` hierarchy. I would suggest moving everything in the data_browser.py file in the __init__.py to make this simpler. The viewers imports can be removed as well.

**Comment by edbarnard** [comment]
ScopeFoundry v1.2.3 includes this fix
